image: Visual Studio 2017

configuration: Release 
  
before_build:
  - nuget restore

build:
  project: Atdl4net.sln
  verbosity: minimal

deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/cristina-tapes-7qs0g4us7vw4/api/v2/package
    api_key:
      secure: 3QOcYJQfDzYQTMmXxWrKKZaRlHDWwZQIdrFnQWbx7dk=
    artifact: /.*\.symbols\.nupkg/